Task 4
evTyurin/SENLA-java-courses pull request #6
Opened 2023-07-11 13:55 UTC by evTyurin

Complete task 4

2023-07-12 09:50 UTC, mrseneca requested changes
Proper git-flow needed.
We agreed to merge 3.4 task into some branch what will be development branch for future.
But your [Electronic_car_service_administrator](https://github.com/evTyurin/SENLA-java-courses/tree/Electronic_car_service_administrator) branch is empty
You can look up Mark's comment about this topic in our skype chat

2023-07-12 16:52 UTC, evTyurin commented
My bad. I moved my commits from [Task 3.4](https://github.com/evTyurin/SENLA-java-courses/tree/TASK_3.4) to [Electronic_car_service_administrator](https://github.com/evTyurin/SENLA-java-courses/tree/Electronic_car_service_administrator) previously but didn't push it. Now I fixed it.

2023-07-12 20:11 UTC, mrseneca requested changes
Good job, but you need to fix the architecture to make it easier for you to develop in the future and use best practices

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/entity/Garage.java
> +public class Garage {
Why exactly you need Entity, Repo and Service for Garage? I thought your FULL application should represent some Garage. But right now looks like you have a bunch of garages, with bunch of mechanics. Lets not do this, and change for Garage representation.

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/entity/Garage.java
> +public class Garage {
So this entity, repo for it and also service should be deleted.

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/entity/OrderStatus.java
> +public enum OrderStatus {
It's not Entity, so you can move it to different package: util or variable for example

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/entity/Craftsman.java
> +    private Map<LocalDateTime, Boolean> schedule;
No, scheduling should not be part of the mechanic. "Schedule" will be an abstraction that is based on orders. In the order, you must have the date of its execution, the id of the mechanic and the id of the place in the garage. And based on this, on the go it is necessary to calculate when and who is free on a certain date. There is no need to store it, especially in the entity mechanic

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/entity/GaragePlace.java
> +    private Map<LocalDateTime, Boolean> schedule;
Same about schedule as for mechanic

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/service/GaragePlaceService.java
> +    private ICraftsmanDAO craftsmanDAO;
Unfortunately, it is bad practice to use someone else's dao in an inappropriate service. If you really need to work with the mechanics in this service, you can do it through the mechanics service, not through the dao.

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/service/GaragePlaceService.java
> +    private ICraftsmanDAO craftsmanDAO;
But think about pass desired mechanic to method what need it, if it's possible.

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/Test.java
> +        Craftsman bob = new Craftsman();
Mechanics, orders and garage places should be created on Service layer, not here (you can count it as Controller layer).
So pass needed variables to service methods and in there create entities and save them to dao

2023-07-12 20:11 UTC, mrseneca commented on src/com/senlainc/warsaw/tyurin/Test.java
> +        GaragePlaceDAO garagePlaceDAO = GaragePlaceDAO.getInstance();
You can not operate with dao on this layer, here you can operate only with Service.
So as i wrote in comment before, create and save entities through service methods

2023-07-27 15:04 UTC, mrseneca approved these changes
That will do work for now. Still some small issues in code and architecture, but wil will fix them later. Good job

2023-07-28 19:13 UTC, evTyurin commented
> That will do work for now. Still some small issues in code and architecture, but wil will fix them later. Good job

Thank you :)

2023-08-07 17:53 UTC, merged