Task 6
evTyurin/SENLA-java-courses pull request #8
Opened 2023-08-17 19:14 UTC by evTyurin

2023-08-19 11:42 UTC, Mark005 requested changes

2023-08-19 11:42 UTC, Mark005 commented on src/resources/craftsmen.csv
> +id:1,name:bob,surname:smith
your data format in CSV file  is incorrect you shouldn't have a key-value format for each field but you have to write data with a header as a first line and data in others 
![image](https://github.com/evTyurin/SENLA-java-courses/assets/39222770/cd5f9625-7767-4982-9e8c-bdf9f10a5bb0)

2023-08-19 11:46 UTC, Mark005 commented on src/com/senlainc/warsaw/tyurin/service/OrderService.java
> +                    throw new IllegalArgumentException("You enter not a date as submission date");
you throw the exceptions but where do you handle them??

2023-08-22 20:31 UTC, mrseneca approved these changes
Good job

2023-08-24 17:49 UTC, evTyurin commented
> 

Thanks :)

2023-08-26 10:06 UTC, merged