Task_7
evTyurin/SENLA-java-courses pull request #9
Opened 2023-08-27 19:57 UTC by evTyurin

2023-08-30 13:04 UTC, mrseneca requested changes
Let's change a bit code from previous task and some code from this task. Move export/import/json-serialization from dao to service layer. It will be better for future development

2023-08-30 13:04 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/dao/CraftsmanDAO.java
> +    private JsonReader jsonReader;
I missed it last time I reviewed your task. my bad
Dao layer work with data, no need to bring here export/import work. 
Move this to service layer, work with export there and pass in dao already prepared entities

2023-08-30 13:04 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/service/CraftsmanService.java
> +        craftsmanDAO.exportCraftsmenToCsv(craftsmen, Constants.PATH_TO_CRAFTSMEN_CSV);
Same here, Entity should only contain info about itself and be able to provide api for crud-operations. 
And not it's also know how to write/read itself from/to external source.
Move this logic to service layer

2023-08-31 20:07 UTC, evTyurin commented
> Let's change a bit code from previous task and some code from this task. Move export/import/json-serialization from dao to service layer. It will be better for future development

Done

2023-09-01 08:09 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/util/Constants.java
> +    public static String PATH_TO_CRAFTSMEN_CSV = "src\\main\\resources\\craftsmen.csv";
When you use relative paths, you may experience problems running the application on other operating systems. Your property files are already in resources, which means they are in the classpath. You can specify paths taking into account the classpath, i.e. PATH_TO_PROPERTIES = "application.properties";

Additionally, you just need to change how you read property files, don't refer to them as files, but use the classloader to refer to them as resources

2023-09-01 08:13 UTC, mrseneca requested changes
Almost done. Just few tunes

2023-09-01 08:13 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/util/Constants.java
> +    public static String PATH_TO_CRAFTSMEN_CSV = "src\\main\\resources\\craftsmen.csv";
When you use relative paths, you may experience problems running the application on other operating systems. Your property files are already in resources, which means they are in the classpath. You can specify paths taking into account the classpath, i.e. PATH_TO_PROPERTIES = "application.properties";

Additionally, you just need to change how you read property files, don't refer to them as files, but use the classloader to refer to them as resources

2023-09-01 08:13 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/util/propertyHandlers/PropertyReader.java
> +        try (InputStream input = new FileInputStream(path)) {
`InputStream input = PropertyReader.class.getClassLoader().getResourceAsStream(path)`

You can do it like this (check it by yourself, i didn't tested it)

2023-09-01 08:13 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/util/propertyHandlers/PropertyReader.java
> +    public String readProperties(String propertyName, String path) {
Also there is some performance issue - every time you try to get some property you rereading property file, i think it unnecessary, make it read property one time, and then get them from Property class

2023-09-04 20:57 UTC, mrseneca requested changes
Only two small things

2023-09-04 20:57 UTC, mrseneca commented on resources/craftsmen.json
> +[{"id":1,"name":"bob","surname":"smith"},{"id":3,"name":"stan","surname":"smith"},{"id":6,"name":"bob","surname":"smith"},{"id":2,"name":"john","surname":"pops"}]
Just curious. Why you need "red" resource folder when you already have "green" one?
![изображение](https://github.com/evTyurin/SENLA-java-courses/assets/31473268/daa812e7-4655-4696-9122-582dfd3ada9d)

If there is no any idea behind it, please move all source files to a proper one folder

2023-09-04 20:57 UTC, mrseneca commented on src/main/java/com/senlainc/warsaw/tyurin/util/propertyHandlers/PropertyReader.java
> +            propertiesMap.putAll(properties.entrySet()
Why create additional Object for properties? You already have Properties class here. Just use properties.getProperty(key).
No need for additional object

2023-09-05 18:50 UTC, evTyurin commented on resources/craftsmen.json
> +[{"id":1,"name":"bob","surname":"smith"},{"id":3,"name":"stan","surname":"smith"},{"id":6,"name":"bob","surname":"smith"},{"id":2,"name":"john","surname":"pops"}]
As you said before use of relative paths may cause problems running the application on other operating systems. So the idea was to simplify relative path by using only one folder from root folder

2023-09-05 19:13 UTC, mrseneca commented on resources/craftsmen.json
> +[{"id":1,"name":"bob","surname":"smith"},{"id":3,"name":"stan","surname":"smith"},{"id":6,"name":"bob","surname":"smith"},{"id":2,"name":"john","surname":"pops"}]
Yeah, that's right, but there 2 folders rn. You can store all files in one folder under main package (where application.properties stored rn)

2023-09-10 05:21 UTC, mrseneca approved these changes
Good job

2023-09-11 20:02 UTC, merged